DISTFILES+=	fft2d.tgz:ooura \
		eigen-4e696901f873a2347f76d931cf2f701e31e15d05.tar.gz:eigen \
		43ef2148c0936ebf7cb4be6b19927a9d9d145b8f.tar.gz:abseil \
		bazel-skylib.0.8.0.tar.gz:skylib \
		bazel_skylib-0.9.0.tar.gz:skylib1 \
		92dd8a7a518a2fb7ba992d47c8b38299fe0be825.tar.gz:toolchain \
		0d5f3f2768c6ca2faca0079a997a97ce22997a0c.zip:rulescc \
		308b05b2419edb5c8ee0471b67a40403df940149.tar.gz:closure \
		rules_docker-v0.10.0.tar.gz:docker \
		rules_swift.0.12.1.tar.gz:swift \
		816a4ae622e964763ca0862d9dbd19324a1eaf45.tar.gz:farmhash \
		12fed0cd7cfcd9e169bf1925bc3a7a58725fdcc3.zip:gemmlowp \
		fd3d9af80465e4383162e4a7c5e2f406e82dd968.tar.gz:highwayhash \
		506cfa4bffd060c06ec338ce50ea3468daa6c814.tar.gz:re2 \
		36dbc057604f00aacfc0288ddad57e3b21cfc1b8.tar.gz:kissfft \
		v2.3.0.tar.gz:pybind \
		ecc999101aadc8dc7d4af9fd88be10fe42674aa0.tar.gz:llvm \
		1200fe90bb174a6224a525ee60148671a786a71f.tar.gz:neon \
		license.rst.txt:license \
		backports.weakref-1.0rc1.tar.gz:weakref

MASTER_SITES+=	https://storage.googleapis.com/mirror.tensorflow.org/www.kurims.kyoto-u.ac.jp/~ooura/:ooura \
		https://gitlab.com/libeigen/eigen/-/archive/4e696901f873a2347f76d931cf2f701e31e15d05/:eigen \
		https://github.com/abseil/abseil-cpp/archive/:abseil \
		https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/:skylib \
		https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/:skylib1 \
		https://github.com/bazelbuild/bazel-toolchains/archive/:toolchain \
		https://github.com/bazelbuild/rules_cc/archive/:rulescc \
		https://github.com/bazelbuild/rules_closure/archive/:closure \
		https://github.com/bazelbuild/rules_docker/releases/download/v0.10.0/:docker \
		https://github.com/bazelbuild/rules_swift/releases/download/0.12.1/:swift \
		https://github.com/google/farmhash/archive/:farmhash \
		https://github.com/google/gemmlowp/archive/:gemmlowp \
		https://github.com/google/highwayhash/archive/:highwayhash \
		https://github.com/google/re2/archive/:re2 \
		https://github.com/mborgerding/kissfft/archive/:kissfft \
		https://github.com/pybind/pybind11/archive/:pybind \
		https://github.com/llvm/llvm-project/archive/:llvm \
		https://github.com/intel/ARM_NEON_2_x86_SSE/archive/:neon \
		https://storage.googleapis.com/mirror.tensorflow.org/docs.python.org/2.7/_sources/:license \
		https://pypi.python.org/packages/bc/cc/3cdb0a02e7e96f6c70bd971bc8a90b8463fda83e264fa9c5c1c98ceabd81/:weakref
