PORTNAME=       gast
PORTVERSION=    0.2.2
CATEGORIES=     devel python
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}
DISTNAME=       gast-${PORTVERSION}
MASTER_SITES=   https://pypi.io/packages/source/g/gast/
COMMENT=        AST that abstracts the underlying Python version

LICENSE=        BSD

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

