PORTNAME=       absl
PORTVERSION=    0.7.1
CATEGORIES=     devel python
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}
DISTNAME=       absl-py-${PORTVERSION}
MASTER_SITES=    https://pypi.python.org/packages/source/a/absl-py/
COMMENT=        Abseil Python Common Libraries

LICENSE=        APACHE20

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

