PORTNAME=	google-pasta
PORTVERSION=	0.1.7
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	${PORTNAME}-${PORTVERSION}
MASTER_SITES=	https://pypi.python.org/packages/source/g/${PORTNAME}/
COMMENT=	Library to refactor python code through AST manipulation
MAINTAINER=	amzo1337@gmail.com
LICENSE=        APACHE20

USES=           python
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>

